// <auto-generated />
using System;
using JobPortal.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace JobPortal.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260513152141_AddAuthModule")]
    partial class AddAuthModule
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("JobPortal.API.Entities.RefreshToken", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreatedByIp")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("ReplacedByTokenHash")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("RevokedByIp")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("refresh_tokens");
                });

            modelBuilder.Entity("JobPortal.API.Entities.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<DateTime?>("PasswordResetTokenExpiresAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("PasswordResetTokenHash")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("users");
                });

            modelBuilder.Entity("JobPortal.API.Models.CongViec", b =>
                {
                    b.Property<long>("IdCongViec")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id_cong_viec");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("IdCongViec"));

                    b.Property<string>("DiaDiem")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("dia_diem");

                    b.Property<long>("IdDanhMuc")
                        .HasColumnType("bigint")
                        .HasColumnName("id_danh_muc");

                    b.Property<long>("IdTuyenDung")
                        .HasColumnType("bigint")
                        .HasColumnName("id_tuyen_dung");

                    b.Property<string>("MoTa")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("mo_ta");

                    b.Property<int>("MucLuong")
                        .HasColumnType("int")
                        .HasColumnName("muc_luong");

                    b.Property<DateTime>("NgayBatDau")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("ngay_bat_dau");

                    b.Property<DateTime>("NgayHetHan")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("ngay_het_han");

                    b.Property<DateTime>("NgayKetThuc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("ngay_ket_thuc");

                    b.Property<string>("TieuDe")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("tieu_de");

                    b.Property<string>("TrangThaiBaiDang")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)")
                        .HasColumnName("trang_thai_bai_dang");

                    b.HasKey("IdCongViec");

                    b.HasIndex("IdDanhMuc");

                    b.HasIndex("IdTuyenDung");

                    b.ToTable("cong_viec");
                });

            modelBuilder.Entity("JobPortal.API.Models.DanhGia", b =>
                {
                    b.Property<long>("IdDanhGia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id_danh_gia");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("IdDanhGia"));

                    b.Property<string>("BinhLuan")
                        .HasColumnType("text")
                        .HasColumnName("binh_luan");

                    b.Property<string>("DanhGiaToi")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)")
                        .HasColumnName("danh_gia_toi");

                    b.Property<int>("Diem")
                        .HasColumnType("int")
                        .HasColumnName("danh_gia");

                    b.Property<long>("IdCongViec")
                        .HasColumnType("bigint")
                        .HasColumnName("id_cong_viec");

                    b.Property<long>("IdTimViec")
                        .HasColumnType("bigint")
                        .HasColumnName("id_tim_viec");

                    b.Property<long>("IdTuyenDung")
                        .HasColumnType("bigint")
                        .HasColumnName("id_tuyen_dung");

                    b.HasKey("IdDanhGia");

                    b.HasIndex("IdCongViec");

                    b.HasIndex("IdTimViec");

                    b.HasIndex("IdTuyenDung");

                    b.ToTable("danh_gia");
                });

            modelBuilder.Entity("JobPortal.API.Models.DanhMuc", b =>
                {
                    b.Property<long>("IdDanhMuc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id_danh_muc");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("IdDanhMuc"));

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("ten");

                    b.HasKey("IdDanhMuc");

                    b.ToTable("danh_muc");
                });

            modelBuilder.Entity("JobPortal.API.Models.GoiBaiDang", b =>
                {
                    b.Property<long>("IdGoi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id_goi");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("IdGoi"));

                    b.Property<int>("Gia")
                        .HasColumnType("int")
                        .HasColumnName("gia");

                    b.Property<long>("IdQuanTri")
                        .HasColumnType("bigint")
                        .HasColumnName("id_quan_tri");

                    b.Property<int>("SoLuotDangBai")
                        .HasColumnType("int")
                        .HasColumnName("so_luot_dang_bai");

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("ten");

                    b.HasKey("IdGoi");

                    b.HasIndex("IdQuanTri");

                    b.ToTable("goi_bai_dang");
                });

            modelBuilder.Entity("JobPortal.API.Models.HinhAnh", b =>
                {
                    b.Property<long>("IdHinhAnh")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id_hinh_anh");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("IdHinhAnh"));

                    b.Property<string>("DuongDanUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("duong_dan_url");

                    b.Property<long>("IdCongViec")
                        .HasColumnType("bigint")
                        .HasColumnName("id_cong_viec");

                    b.Property<string>("Ten")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("ten");

                    b.HasKey("IdHinhAnh");

                    b.HasIndex("IdCongViec");

                    b.ToTable("hinh_anh");
                });

            modelBuilder.Entity("JobPortal.API.Models.HoSoTuyenDung", b =>
                {
                    b.Property<long>("IdCv")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id_cv");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("IdCv"));

                    b.Property<long>("IdTimViec")
                        .HasColumnType("bigint")
                        .HasColumnName("id_tim_viec");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("ngay_tao");

                    b.Property<string>("TieuDe")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("tieu_de");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("url");

                    b.HasKey("IdCv");

                    b.HasIndex("IdTimViec");

                    b.ToTable("ho_so_tuyen_dung");
                });

            modelBuilder.Entity("JobPortal.API.Models.LichSuThanhToan", b =>
                {
                    b.Property<long>("IdThanhToan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id_thanh_toan");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("IdThanhToan"));

                    b.Property<int>("Gia")
                        .HasColumnType("int")
                        .HasColumnName("gia");

                    b.Property<string>("IdDonHang")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("id_don_hang");

                    b.Property<long>("IdGoi")
                        .HasColumnType("bigint")
                        .HasColumnName("id_goi");

                    b.Property<long>("IdTuyenDung")
                        .HasColumnType("bigint")
                        .HasColumnName("id_tuyen_dung");

                    b.Property<string>("MaGiaoDich")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("ma_giao_dich");

                    b.Property<string>("NganHangThanhToan")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("ngan_hang_thanh_toan");

                    b.Property<DateTime?>("NgayThanhToan")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("ngay_thanh_toan");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)")
                        .HasColumnName("trang_thai");

                    b.HasKey("IdThanhToan");

                    b.HasIndex("IdGoi");

                    b.HasIndex("IdTuyenDung");

                    b.ToTable("lich_su_thanh_toan");
                });

            modelBuilder.Entity("JobPortal.API.Models.NguoiTimViec", b =>
                {
                    b.Property<long>("IdTimViec")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id_tim_viec");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("IdTimViec"));

                    b.Property<string>("AnhDaiDien")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("anh_dai_dien");

                    b.Property<string>("Cccd")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("cccd");

                    b.Property<string>("DiaChiTamTru")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("dia_chi_tam_tru");

                    b.Property<string>("DiaChiThuongTru")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("dia_chi_thuong_tru");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("email");

                    b.Property<DateTime?>("EmailXacThuc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("email_xac_thuc");

                    b.Property<byte?>("GioiTinh")
                        .HasColumnType("tinyint unsigned")
                        .HasColumnName("gioi_tinh");

                    b.Property<string>("MatKhau")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("mat_khau");

                    b.Property<string>("MoTa")
                        .HasColumnType("text")
                        .HasColumnName("mo_ta");

                    b.Property<string>("NgayCapCccd")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("ngay_cap_cccd");

                    b.Property<DateOnly?>("NgaySinh")
                        .HasColumnType("date")
                        .HasColumnName("ngay_sinh");

                    b.Property<string>("NoiCap")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("noi_cap");

                    b.Property<string>("Sdt")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("sdt");

                    b.Property<string>("SoTaiKhoan")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("so_tai_khoan");

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("ten");

                    b.Property<string>("TenNganHang")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("ten_ngan_hang");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)")
                        .HasColumnName("trang_thai");

                    b.HasKey("IdTimViec");

                    b.ToTable("nguoi_tim_viec");
                });

            modelBuilder.Entity("JobPortal.API.Models.NhaTuyenDung", b =>
                {
                    b.Property<long>("IdTuyenDung")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id_tuyen_dung");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("IdTuyenDung"));

                    b.Property<string>("Anh")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("anh");

                    b.Property<string>("Cccd")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("cccd");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("email");

                    b.Property<DateTime?>("EmailXacThuc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("email_xac_thuc");

                    b.Property<byte?>("GioiTinh")
                        .HasColumnType("tinyint unsigned")
                        .HasColumnName("gioi_tinh");

                    b.Property<string>("MatKhau")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("mat_khau");

                    b.Property<string>("MoTa")
                        .HasColumnType("text")
                        .HasColumnName("mo_ta");

                    b.Property<DateOnly?>("NgaySinh")
                        .HasColumnType("date")
                        .HasColumnName("ngay_sinh");

                    b.Property<string>("Sdt")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("sdt");

                    b.Property<int>("SoLuotBaiDang")
                        .HasColumnType("int")
                        .HasColumnName("so_luot_bai_dang");

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("ten");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)")
                        .HasColumnName("trang_thai");

                    b.HasKey("IdTuyenDung");

                    b.ToTable("nha_tuyen_dung");
                });

            modelBuilder.Entity("JobPortal.API.Models.QuaTrinhLamViec", b =>
                {
                    b.Property<long>("IdLamViec")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id_lam_viec");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("IdLamViec"));

                    b.Property<long>("IdUngTuyen")
                        .HasColumnType("bigint")
                        .HasColumnName("id_ung_tuyen");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)")
                        .HasColumnName("trang_thai");

                    b.HasKey("IdLamViec");

                    b.HasIndex("IdUngTuyen");

                    b.ToTable("qua_trinh_lam_viec");
                });

            modelBuilder.Entity("JobPortal.API.Models.QuanTriVien", b =>
                {
                    b.Property<long>("IdQuanTri")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id_quan_tri");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("IdQuanTri"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("email");

                    b.Property<string>("MatKhau")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("mat_khau");

                    b.Property<string>("SoTaiKhoan")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("so_tai_khoan");

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("ten");

                    b.Property<string>("TenNganHang")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("ten_ngan_hang");

                    b.HasKey("IdQuanTri");

                    b.ToTable("quan_tri_vien");
                });

            modelBuilder.Entity("JobPortal.API.Models.UngTuyen", b =>
                {
                    b.Property<long>("IdUngTuyen")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id_ung_tuyen");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("IdUngTuyen"));

                    b.Property<long>("IdCongViec")
                        .HasColumnType("bigint")
                        .HasColumnName("id_cong_viec");

                    b.Property<long>("IdCv")
                        .HasColumnType("bigint")
                        .HasColumnName("id_cv");

                    b.Property<long>("IdTimViec")
                        .HasColumnType("bigint")
                        .HasColumnName("id_tim_viec");

                    b.Property<DateTime>("NgayUngTuyen")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("ngay_ung_tuyen");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)")
                        .HasColumnName("trang_thai");

                    b.HasKey("IdUngTuyen");

                    b.HasIndex("IdCongViec");

                    b.HasIndex("IdCv");

                    b.HasIndex("IdTimViec");

                    b.ToTable("ung_tuyen");
                });

            modelBuilder.Entity("JobPortal.API.Entities.RefreshToken", b =>
                {
                    b.HasOne("JobPortal.API.Entities.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("JobPortal.API.Models.CongViec", b =>
                {
                    b.HasOne("JobPortal.API.Models.DanhMuc", "DanhMuc")
                        .WithMany("CongViecs")
                        .HasForeignKey("IdDanhMuc")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("JobPortal.API.Models.NhaTuyenDung", "NhaTuyenDung")
                        .WithMany("CongViecs")
                        .HasForeignKey("IdTuyenDung")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DanhMuc");

                    b.Navigation("NhaTuyenDung");
                });

            modelBuilder.Entity("JobPortal.API.Models.DanhGia", b =>
                {
                    b.HasOne("JobPortal.API.Models.CongViec", "CongViec")
                        .WithMany("DanhGias")
                        .HasForeignKey("IdCongViec")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("JobPortal.API.Models.NguoiTimViec", "NguoiTimViec")
                        .WithMany("DanhGias")
                        .HasForeignKey("IdTimViec")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("JobPortal.API.Models.NhaTuyenDung", "NhaTuyenDung")
                        .WithMany("DanhGias")
                        .HasForeignKey("IdTuyenDung")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CongViec");

                    b.Navigation("NguoiTimViec");

                    b.Navigation("NhaTuyenDung");
                });

            modelBuilder.Entity("JobPortal.API.Models.GoiBaiDang", b =>
                {
                    b.HasOne("JobPortal.API.Models.QuanTriVien", "QuanTriVien")
                        .WithMany("GoiBaiDangs")
                        .HasForeignKey("IdQuanTri")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("QuanTriVien");
                });

            modelBuilder.Entity("JobPortal.API.Models.HinhAnh", b =>
                {
                    b.HasOne("JobPortal.API.Models.CongViec", "CongViec")
                        .WithMany("HinhAnhs")
                        .HasForeignKey("IdCongViec")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CongViec");
                });

            modelBuilder.Entity("JobPortal.API.Models.HoSoTuyenDung", b =>
                {
                    b.HasOne("JobPortal.API.Models.NguoiTimViec", "NguoiTimViec")
                        .WithMany("HoSoTuyenDungs")
                        .HasForeignKey("IdTimViec")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NguoiTimViec");
                });

            modelBuilder.Entity("JobPortal.API.Models.LichSuThanhToan", b =>
                {
                    b.HasOne("JobPortal.API.Models.GoiBaiDang", "GoiBaiDang")
                        .WithMany("LichSuThanhToans")
                        .HasForeignKey("IdGoi")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("JobPortal.API.Models.NhaTuyenDung", "NhaTuyenDung")
                        .WithMany("LichSuThanhToans")
                        .HasForeignKey("IdTuyenDung")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("GoiBaiDang");

                    b.Navigation("NhaTuyenDung");
                });

            modelBuilder.Entity("JobPortal.API.Models.QuaTrinhLamViec", b =>
                {
                    b.HasOne("JobPortal.API.Models.UngTuyen", "UngTuyen")
                        .WithMany("QuaTrinhLamViecs")
                        .HasForeignKey("IdUngTuyen")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UngTuyen");
                });

            modelBuilder.Entity("JobPortal.API.Models.UngTuyen", b =>
                {
                    b.HasOne("JobPortal.API.Models.CongViec", "CongViec")
                        .WithMany("UngTuyens")
                        .HasForeignKey("IdCongViec")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("JobPortal.API.Models.HoSoTuyenDung", "HoSoTuyenDung")
                        .WithMany("UngTuyens")
                        .HasForeignKey("IdCv")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("JobPortal.API.Models.NguoiTimViec", "NguoiTimViec")
                        .WithMany("UngTuyens")
                        .HasForeignKey("IdTimViec")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CongViec");

                    b.Navigation("HoSoTuyenDung");

                    b.Navigation("NguoiTimViec");
                });

            modelBuilder.Entity("JobPortal.API.Entities.User", b =>
                {
                    b.Navigation("RefreshTokens");
                });

            modelBuilder.Entity("JobPortal.API.Models.CongViec", b =>
                {
                    b.Navigation("DanhGias");

                    b.Navigation("HinhAnhs");

                    b.Navigation("UngTuyens");
                });

            modelBuilder.Entity("JobPortal.API.Models.DanhMuc", b =>
                {
                    b.Navigation("CongViecs");
                });

            modelBuilder.Entity("JobPortal.API.Models.GoiBaiDang", b =>
                {
                    b.Navigation("LichSuThanhToans");
                });

            modelBuilder.Entity("JobPortal.API.Models.HoSoTuyenDung", b =>
                {
                    b.Navigation("UngTuyens");
                });

            modelBuilder.Entity("JobPortal.API.Models.NguoiTimViec", b =>
                {
                    b.Navigation("DanhGias");

                    b.Navigation("HoSoTuyenDungs");

                    b.Navigation("UngTuyens");
                });

            modelBuilder.Entity("JobPortal.API.Models.NhaTuyenDung", b =>
                {
                    b.Navigation("CongViecs");

                    b.Navigation("DanhGias");

                    b.Navigation("LichSuThanhToans");
                });

            modelBuilder.Entity("JobPortal.API.Models.QuanTriVien", b =>
                {
                    b.Navigation("GoiBaiDangs");
                });

            modelBuilder.Entity("JobPortal.API.Models.UngTuyen", b =>
                {
                    b.Navigation("QuaTrinhLamViecs");
                });
#pragma warning restore 612, 618
        }
    }
}
